import type { ConnectorDefinition, ConnectorTypicalImportance } from "./types.js";

const M = "recommended" as ConnectorTypicalImportance;
const O = "optional" as ConnectorTypicalImportance;

function steps(...lines: string[]): string[] {
  return lines;
}

/** Extended catalog entries — merged into {@link CONNECTOR_CATALOG} in `catalog.ts`. */
export const ADDITIONAL_CONNECTORS: ConnectorDefinition[] = [
  {
    id: "figma",
    stackIcon: "figma",
    name: "Figma",
    category: "design_research",
    description:
      "UI design files, components, dev-mode specs, and comments — primary home for product/design craft.",
    typicalImportance: M,
    audiences: ["design", "product", "engineering"],
    keywords: ["design system", "prototype", "handoff", "UX", "UI"],
    setupOverview:
      "Figma access is highly sensitive: files often embed strategy and unreleased work. Prefer team-scoped OAuth or service accounts with explicit project folders.",
    rolloutNotes: [
      "Decide read-only vs comment vs edit — editing should be rare for coworkers unless policy allows.",
      "Mirror your design-file taxonomy (project → file → page) in documentation so operators know what is in bounds.",
    ],
    authenticationNotes: [
      "Use OAuth with minimal scopes; enable SCIM or SSO alignment if your org uses Enterprise.",
      "Rotate personal access tokens used for pilots; prefer OAuth for production.",
    ],
    setupSteps: steps(
      "Register a Figma OAuth app in the team or org settings; capture callback URL from Bench connector settings when available.",
      "Request scopes limited to file/content read (and optional comments) — exclude billing or admin unless required.",
      "Complete OAuth as a design org admin; verify the app appears under approved integrations.",
      "Enumerate starter files or projects the coworker may index; exclude HR/legal archives explicitly.",
      "Open a sample file via API or connector health check to validate token TTL and refresh behavior.",
    ),
    learnMoreUrl: "https://www.figma.com/developers/api",
  },
  {
    id: "framer",
    stackIcon: "framer",
    name: "Framer",
    category: "design_research",
    description: "Marketing sites and interactive prototypes published from Framer.",
    typicalImportance: O,
    audiences: ["design", "product", "gtm"],
    keywords: ["website", "landing page", "CMS"],
    setupOverview:
      "Framer blends design and publishing. Separate staging vs production sites before granting automation access.",
    setupSteps: steps(
      "Create or reuse a Framer workspace API token with least privilege.",
      "List site IDs the coworker may read or publish to.",
      "Confirm DNS / SSL ownership policies if coworkers trigger publishes.",
      "Run a read-only fetch of site metadata to validate connectivity.",
      "Document rollback expectations if automated publishes are ever enabled.",
    ),
    learnMoreUrl: "https://www.framer.com/developers/",
  },
  {
    id: "sketch",
    stackIcon: "sketch",
    name: "Sketch",
    category: "design_research",
    description: "macOS-native design files and libraries common in native/mobile-heavy teams.",
    typicalImportance: O,
    audiences: ["design", "product"],
    keywords: ["mockups", "symbols", "libraries"],
    setupOverview:
      "Sketch Cloud APIs expose documents and versions — align with how designers already share links internally.",
    setupSteps: steps(
      "Generate a personal access token from Sketch account settings.",
      "Map document URLs or workspace IDs allowed for sync.",
      "Verify read permissions on libraries referenced by those documents.",
      "Perform a metadata-only fetch test against a non-sensitive file.",
      "Plan token rotation with design ops.",
    ),
    learnMoreUrl: "https://developer.sketch.com/",
  },
  {
    id: "miro",
    stackIcon: "miro",
    name: "Miro",
    category: "design_research",
    description: "Infinite canvases for workshops, journey maps, and discovery artifacts.",
    typicalImportance: M,
    audiences: ["design", "product", "engineering"],
    keywords: ["whiteboard", "workshop", "discovery"],
    setupOverview:
      "Miro boards often contain photos of whiteboards and sticky notes that qualify as sensitive — restrict boards by team space.",
    setupSteps: steps(
      "Create a Miro OAuth client or use Enterprise-managed apps per vendor guidance.",
      "Scope to specific teams and boards — avoid full-org discovery.",
      "Decide whether coworkers only ingest snapshots vs live boards.",
      "Invite the integration user or service principal to pilot boards.",
      "Validate export/read APIs against a sanitized template board.",
    ),
    learnMoreUrl: "https://developers.miro.com/",
  },
  {
    id: "adobe-xd",
    stackIcon: "xd",
    name: "Adobe XD",
    category: "design_research",
    description: "Design specs and prototypes for teams still on Adobe’s UX toolchain.",
    typicalImportance: O,
    audiences: ["design"],
    keywords: ["prototype", "Adobe"],
    setupOverview:
      "Adobe is migrating many teams toward other tools — confirm XD is still strategic before investing integration effort.",
    setupSteps: steps(
      "Use Adobe Developer Console to register an OAuth integration.",
      "Capture IMS org and project identifiers tied to creative cloud.",
      "Limit scopes to document read where possible.",
      "Run Adobe’s token validation flows from a staging account.",
      "Retire tokens when teams deprecate XD.",
    ),
    learnMoreUrl: "https://developer.adobe.com/xd/cloud/",
  },
  {
    id: "invision",
    stackIcon: "invision",
    name: "InVision",
    category: "design_research",
    description: "Design collaboration and feedback loops where Freehand/prototypes remain in use.",
    typicalImportance: O,
    audiences: ["design", "product"],
    keywords: ["feedback", "comments", "prototype"],
    setupOverview:
      "Many enterprises are consolidating on fewer vendors — verify active contracts before enabling automation.",
    setupSteps: steps(
      "Use InVision REST tokens scoped to the workspace.",
      "Enumerate prototype IDs or boards allowed for crawl.",
      "Disable downloads if policy forbids artifact export.",
      "Verify webhook or polling limits for comment streams.",
      "Align retention with legal when copying comments elsewhere.",
    ),
    learnMoreUrl: "https://developer.invisionapp.com/",
  },
  {
    id: "canva",
    stackIcon: "canva",
    name: "Canva",
    category: "design_research",
    description: "Template-driven graphics for marketing, employer brand, and lightweight collateral.",
    typicalImportance: O,
    audiences: ["design", "gtm", "people"],
    keywords: ["templates", "brand", "social"],
    setupOverview:
      "Canva folders mix internal and external-ready assets — separate teams by brand vs confidential drafts.",
    setupSteps: steps(
      "Create an OAuth integration via Canva’s developer portal.",
      "Restrict folders or brands accessible to automation.",
      "Confirm licensing for stock assets before automated reuse.",
      "Validate export formats permitted by brand guidelines.",
      "Rotate credentials alongside marketing ops calendars.",
    ),
    learnMoreUrl: "https://www.canva.dev/",
  },
  {
    id: "affinity-designer",
    stackIcon: "affinitydesigner",
    name: "Affinity (Designer / Photo)",
    category: "design_research",
    description: "Vector and raster workflows where teams standardized on Serif Affinity.",
    typicalImportance: O,
    audiences: ["design"],
    keywords: ["illustration", "Serif"],
    setupOverview:
      "Affinity’s automation surfaces are thinner than cloud-native competitors — prefer filesystem + DAM patterns when APIs are insufficient.",
    setupSteps: steps(
      "Inventory whether teams rely on cloud shares vs local packaging.",
      "If APIs exist for your license tier, register developer credentials.",
      "Otherwise document watched folders or export pipelines.",
      "Verify color-profile and font-licensing constraints.",
      "Schedule manual reviews until automated pipelines mature.",
    ),
    learnMoreUrl: "https://affinity.serif.com/",
  },
  {
    id: "dovetail",
    stackIcon: "dovetail",
    name: "Dovetail",
    category: "design_research",
    description: "Qualitative research repository — interviews, highlights, and thematic insights.",
    typicalImportance: M,
    audiences: ["design", "product", "data"],
    keywords: ["user research", "insights", "repository", "tags"],
    setupOverview:
      "Dovetail stores transcripts and recordings — treat it like PHI-lite data unless legally cleared for broader processing.",
    rolloutNotes: [
      "Confirm participant consent covers AI summarization if coworkers ingest transcripts.",
      "Separate workspaces for regulated vs general research.",
    ],
    authenticationNotes: [
      "Use API keys tied to service principals with workspace boundaries.",
      "Audit exports — highlights can contain names and customer identifiers.",
    ],
    setupSteps: steps(
      "Generate an API key from Dovetail workspace settings with read-only posture initially.",
      "List channels/projects approved for summarization.",
      "Verify tagging taxonomy matches how PM/design expects insights grouped.",
      "Run a dry-run export of a redacted highlight reel.",
      "Document escalation when sensitive interviews must never leave Dovetail.",
    ),
    learnMoreUrl: "https://developers.dovetail.com/",
  },
  {
    id: "hotjar",
    stackIcon: "hotjar",
    name: "Hotjar",
    category: "design_research",
    description: "Heatmaps, session replay context (policy-dependent), and on-site feedback widgets.",
    typicalImportance: O,
    audiences: ["product", "design", "gtm"],
    keywords: ["analytics", "UX", "sessions"],
    setupOverview:
      "Session replay can capture credentials and personal data — align with privacy/legal before any coworker consumes replays.",
    prerequisites: ["Often blocked or heavily redacted in regulated industries."],
    setupSteps: steps(
      "Confirm legal posture for replay retention and masking.",
      "Use Hotjar API keys scoped to sites/environments approved for analysis.",
      "Restrict sensitive routes via suppression lists.",
      "Validate heatmap snapshots exclude authenticated employee-only pages unless allowed.",
      "Schedule quarterly access reviews.",
    ),
    learnMoreUrl: "https://help.hotjar.com/hc/en-us/articles/115011639887-Hotjar-API",
  },
  {
    id: "clickup",
    stackIcon: "clickup",
    name: "ClickUp",
    category: "delivery",
    description: "Tasks, docs, and goals in one workspace — common for hybrid product/ops teams.",
    typicalImportance: O,
    audiences: ["product", "engineering", "operations"],
    keywords: ["tasks", "sprints", "docs"],
    setupOverview:
      "ClickUp’s breadth means scopes balloon quickly — start with one Space and expand deliberately.",
    setupSteps: steps(
      "Create an OAuth app or personal token per ClickUp security guidance.",
      "Mirror hierarchy (workspace → space → folder → list) in allowlists.",
      "Disable privileged admin scopes unless IT approves.",
      "Smoke-test task create/read with a sandbox list.",
      "Document naming conventions so coworkers don’t duplicate trackers.",
    ),
    learnMoreUrl: "https://clickup.com/api",
  },
  {
    id: "trello",
    stackIcon: "trello",
    name: "Trello",
    category: "delivery",
    description: "Card-based boards for lighter-weight coordination and intake queues.",
    typicalImportance: O,
    audiences: ["product", "operations"],
    keywords: ["kanban", "boards", "cards"],
    setupOverview:
      "Trello is simple to adopt — guard against accidental public boards containing confidential OKRs.",
    setupSteps: steps(
      "Generate a Trello API key + token pair or OAuth app.",
      "Enumerate allowed boards and organizations.",
      "Verify board visibility settings (workspace vs private).",
      "Post a test comment via API.",
      "Rotate tokens when PM ownership changes.",
    ),
    learnMoreUrl: "https://developer.atlassian.com/cloud/trello/guides/rest-api/api-introduction/",
  },
  {
    id: "height",
    name: "Height",
    category: "delivery",
    description: "Product-focused task app with chat-like workflows for small teams.",
    typicalImportance: O,
    audiences: ["product", "engineering"],
    keywords: ["tasks", "lists"],
    setupOverview:
      "Height’s API surface evolves quickly — pin versions and monitor changelog alerts.",
    setupSteps: steps(
      "Create an API token from Height workspace settings.",
      "List lists/projects permitted for automation.",
      "Validate CRUD permissions against a staging workspace.",
      "Confirm webhook signatures if using realtime updates.",
      "Maintain owner contacts for token emergencies.",
    ),
    learnMoreUrl: "https://height.app/",
  },
  {
    id: "shortcut",
    name: "Shortcut (formerly Clubhouse)",
    category: "delivery",
    description: "Issue tracking tuned for software teams wanting fewer knobs than enterprise suites.",
    typicalImportance: O,
    audiences: ["engineering", "product"],
    keywords: ["stories", "epics", "kanban"],
    setupOverview:
      "Shortcut tokens map to individual users — prefer dedicated bot users with documented emails.",
    setupSteps: steps(
      "Generate a personal API token for the automation user.",
      "Restrict workspace via membership rather than broad tokens.",
      "Validate story workflows match engineering conventions.",
      "Test milestone/epic linkage reads.",
      "Rotate tokens when employee owners depart.",
    ),
    learnMoreUrl: "https://developer.shortcut.com/",
  },
  {
    id: "monday-com",
    name: "monday.com",
    category: "delivery",
    description: "Work OS boards spanning CRM-lite, projects, and approvals.",
    typicalImportance: O,
    audiences: ["operations", "product", "gtm"],
    keywords: ["boards", "workflow", "CRM"],
    setupOverview:
      "monday.com workspaces sprawl — codify which boards are authoritative vs experimental.",
    setupSteps: steps(
      "Create an OAuth app or API token per account tier instructions.",
      "Map board IDs and column schemas required for automation.",
      "Verify rate limits for bulk reads.",
      "Run updates against a sandbox board before production.",
      "Train owners on undo/restore expectations.",
    ),
    learnMoreUrl: "https://developer.monday.com/",
  },
  {
    id: "airtable",
    stackIcon: "airtable",
    name: "Airtable",
    category: "knowledge",
    description: "Flexible relational databases used as lightweight CRMs, content calendars, and ops trackers.",
    typicalImportance: O,
    audiences: ["operations", "product", "gtm"],
    keywords: ["spreadsheet", "database", "views"],
    setupOverview:
      "Airtable bases often hold customer PII — apply column-level reviews before syncing.",
    setupSteps: steps(
      "Create a personal access token or OAuth integration.",
      "Share only approved bases and tables with the integration account.",
      "Use views as fences — avoid whole-base scans.",
      "Validate attachment policies if coworkers fetch files.",
      "Monitor API quota usage during backfills.",
    ),
    learnMoreUrl: "https://airtable.com/developers/web/api/introduction",
  },
  {
    id: "webflow",
    stackIcon: "webflow",
    name: "Webflow",
    category: "knowledge",
    description: "Visual site builder + CMS collections for marketing sites.",
    typicalImportance: O,
    audiences: ["gtm", "design", "engineering"],
    keywords: ["CMS", "marketing site", "publish"],
    setupOverview:
      "Webflow CMS writes can go live instantly — separate staging sites where possible.",
    setupSteps: steps(
      "Generate a site-scoped API token.",
      "Enumerate CMS collections approved for automation.",
      "Confirm localization and draft vs published behavior.",
      "Dry-run read endpoints before enabling mutations.",
      "Align SEO approvals if meta fields change.",
    ),
    learnMoreUrl: "https://developers.webflow.com/",
  },
  {
    id: "wordpress",
    stackIcon: "wordpress",
    name: "WordPress",
    category: "knowledge",
    description: "CMS for blogs, docs portals, and marketing properties — self-hosted or WP.com.",
    typicalImportance: O,
    audiences: ["gtm", "engineering"],
    keywords: ["blog", "CMS", "content"],
    setupOverview:
      "WordPress plugins alter auth stories — prefer application passwords or OAuth plugins approved by security.",
    setupSteps: steps(
      "Choose REST vs GraphQL vs WP-CLI remote patterns per hosting.",
      "Issue scoped credentials with explicit role caps.",
      "Disable file editors if coworkers never patch themes.",
      "Verify caching/CDN behavior so drafts aren’t leaked.",
      "Keep plugins patched — automate vulnerability alerts.",
    ),
    learnMoreUrl: "https://developer.wordpress.org/rest-api/",
  },
  {
    id: "sanity",
    stackIcon: "sanity",
    name: "Sanity",
    category: "knowledge",
    description: "Structured content lake with real-time Studio — common for composable stacks.",
    typicalImportance: O,
    audiences: ["engineering", "design", "gtm"],
    keywords: ["headless CMS", "content"],
    setupOverview:
      "Sanity datasets blend drafts and published docs — use perspectives or tokens that cannot read drafts if required.",
    setupSteps: steps(
      "Create a Sanity API token with dataset + role constraints.",
      "Document GROQ queries permitted for coworkers.",
      "Separate staging datasets from production.",
      "Validate webhook signatures for inbound events.",
      "Review asset pipeline for PII in uploads.",
    ),
    learnMoreUrl: "https://www.sanity.io/docs/http-reference",
  },
  {
    id: "amplitude",
    stackIcon: "amplitude",
    name: "Amplitude",
    category: "platforms",
    description: "Behavioral analytics and experimentation readouts for product decisions.",
    typicalImportance: O,
    audiences: ["product", "data", "engineering"],
    keywords: ["analytics", "events", "funnels"],
    setupOverview:
      "Amplitude projects aggregate user journeys — confirm residency and sampling rules before exporting insights elsewhere.",
    setupSteps: steps(
      "Create a scoped API or service account key.",
      "List projects/environments allowed for query.",
      "Verify cohort definitions align with privacy labeling.",
      "Dry-run chart export APIs.",
      "Document guardrails for summarizing sensitive populations.",
    ),
    learnMoreUrl: "https://www.docs.developers.amplitude.com/",
  },
  {
    id: "segment",
    stackIcon: "segment",
    name: "Segment (Twilio)",
    category: "platforms",
    description: "Customer data platform routing events to warehouses and downstream tools.",
    typicalImportance: O,
    audiences: ["data", "product", "gtm"],
    keywords: ["CDP", "pipelines", "tracking"],
    setupOverview:
      "Segment touches nearly every downstream system — treat tokens like cloud-admin credentials.",
    setupSteps: steps(
      "Use workspace-scoped tokens with read-only posture unless mutations are approved.",
      "Map sources vs destinations explicitly.",
      "Validate PII scrubbing policies before forwarding to AI summarizers.",
      "Exercise Tracking Plan APIs if schemas are contractual.",
      "Rotate keys on employee transitions.",
    ),
    learnMoreUrl: "https://segment.com/docs/",
  },
  {
    id: "travis-ci",
    stackIcon: "travis",
    name: "Travis CI",
    category: "platforms",
    description: "Hosted CI common in OSS and smaller teams — builds and GitHub checks.",
    typicalImportance: O,
    audiences: ["engineering", "operations"],
    keywords: ["CI", "build", "pipeline"],
    setupOverview:
      "Shared Travis secrets have burned teams before — isolate orgs and rely on OIDC where Travis supports it.",
    setupSteps: steps(
      "Generate API tokens limited to required repositories.",
      "Audit `.travis.yml` secrets usage.",
      "Disable sudo-enabled builds if unnecessary.",
      "Mirror GitHub branch protection expectations.",
      "Monitor build minutes for cost spikes.",
    ),
    learnMoreUrl: "https://docs.travis-ci.com/",
  },
  {
    id: "teamcity",
    stackIcon: "teamcity",
    name: "TeamCity",
    category: "platforms",
    description: "JetBrains CI server — common for JVM-heavy enterprises.",
    typicalImportance: O,
    audiences: ["engineering", "operations"],
    keywords: ["CI", "build"],
    setupOverview:
      "TeamCity often sits on-prem — ensure VPN/bastion paths are documented for automation hosts.",
    setupSteps: steps(
      "Create personal tokens or service accounts with project-level ACLs.",
      "Verify VCS roots exposed to automation.",
      "Confirm artifact storage permissions.",
      "Dry-run build trigger APIs.",
      "Patch TeamCity aggressively — historic RCE issues matter.",
    ),
    learnMoreUrl: "https://www.jetbrains.com/help/teamcity/rest-api.html",
  },
  {
    id: "apache-pulsar",
    stackIcon: "pulsar",
    name: "Apache Pulsar",
    category: "platforms",
    description: "Distributed messaging and streaming — multi-tenant Kafka alternative.",
    typicalImportance: O,
    audiences: ["engineering", "data"],
    keywords: ["streaming", "queues", "events"],
    setupOverview:
      "Pulsar auth spans tenants/namespaces — misconfiguration leaks topics across product lines.",
    setupSteps: steps(
      "Issue tokens scoped to explicit namespaces and topics.",
      "Prefer TLS + JWT/OAuth2 brokers.",
      "Validate backlog retention vs compliance.",
      "Dry-run consume with reader-only roles.",
      "Document compaction/bookkeeping impacts.",
    ),
    learnMoreUrl: "https://pulsar.apache.org/docs/next/security-overview/",
  },
  {
    id: "nats",
    stackIcon: "nats",
    name: "NATS",
    category: "platforms",
    description: "Lightweight messaging backbone for microservices and edge deployments.",
    typicalImportance: O,
    audiences: ["engineering", "operations"],
    keywords: ["pub/sub", "jetstream"],
    setupOverview:
      "NATS credentials are often short-lived — integrate with your secrets manager rotation cadence.",
    setupSteps: steps(
      "Enable authentication (NKeys/JWT) on all routes.",
      "Partition subjects via accounts.",
      "Validate JetStream retention policies.",
      "Exercise subscribe-only users before publishers.",
      "Monitor slow consumers for cascade failures.",
    ),
    learnMoreUrl: "https://docs.nats.io/running-a-nats-service/configuration/securing_nats",
  },
  {
    id: "discord",
    name: "Discord",
    category: "collaboration",
    description: "Community and team chat popular with developer relations and gaming-adjacent orgs.",
    typicalImportance: O,
    audiences: ["engineering", "gtm"],
    keywords: ["community", "voice", "bots"],
    setupOverview:
      "Discord servers blur personal/business boundaries — prefer enterprise-managed servers with MFA enforcement.",
    setupSteps: steps(
      "Create a Discord application and bot user.",
      "Generate tokens with intent flags matching read/post needs.",
      "Restrict bot to approved guilds/channels.",
      "Capture moderation workflows if coworkers post publicly.",
      "Rotate bot tokens if leaked — they grant live access.",
    ),
    learnMoreUrl: "https://discord.com/developers/docs/topics/oauth2",
  },
  {
    id: "loom",
    name: "Loom",
    category: "meetings",
    description: "Async video messages for demos, reviews, and customer updates.",
    typicalImportance: O,
    audiences: ["product", "design", "gtm"],
    keywords: ["video", "async", "recording"],
    setupOverview:
      "Videos may capture screens with confidential data — default to private workspace libraries.",
    setupSteps: steps(
      "Use Loom OAuth scoped to enterprise workspace features.",
      "Disable public links unless comms approves.",
      "Verify transcript retention settings.",
      "Dry-run API reads on a sanitized library.",
      "Train users on blur/redact tooling before recording.",
    ),
    learnMoreUrl: "https://dev.loom.com/",
  },
  {
    id: "zendesk",
    name: "Zendesk",
    category: "platforms",
    description: "Customer support ticketing — macros, views, and SLA-sensitive queues.",
    typicalImportance: O,
    audiences: ["operations", "gtm"],
    keywords: ["support", "CS", "tickets"],
    setupOverview:
      "Zendesk tickets contain customer secrets — least-privilege agents and redaction rules are mandatory.",
    setupSteps: steps(
      "Create OAuth client or API token with explicit role.",
      "Restrict groups/brands accessible to automation.",
      "Disable destructive macros until reviewed.",
      "Exercise read APIs against sandbox tickets.",
      "Alert on unusual comment velocity.",
    ),
    learnMoreUrl: "https://developer.zendesk.com/",
  },
  {
    id: "hubspot-crm",
    name: "HubSpot",
    category: "platforms",
    description: "CRM, marketing automation, and service hubs for GTM teams.",
    typicalImportance: O,
    audiences: ["gtm", "leadership"],
    keywords: ["CRM", "marketing", "sales"],
    setupOverview:
      "HubSpot unions marketing + CRM data — separate portals if regulated verticals mix with broad campaigns.",
    setupSteps: steps(
      "Create a private app or OAuth app with granular scopes.",
      "Record objects (contacts, deals, tickets) allowed for AI enrichment.",
      "Enable audit logs.",
      "Dry-run CRM search APIs with anonymized fixtures.",
      "Coordinate with RevOps on pipeline definitions.",
    ),
    learnMoreUrl: "https://developers.hubspot.com/",
  },
  {
    id: "intercom",
    name: "Intercom",
    category: "platforms",
    description: "In-product messaging, chatbots, and helpdesk workflows.",
    typicalImportance: O,
    audiences: ["gtm", "product"],
    keywords: ["chat", "support", "messenger"],
    setupOverview:
      "Intercom can send outbound messages — dual-control anything that might email thousands of users.",
    setupSteps: steps(
      "Generate access tokens per workspace with minimal scopes.",
      "Separate staging vs production workspaces.",
      "Validate conversation tagging taxonomy.",
      "Dry-run article/help center reads.",
      "Document pause switches for automation.",
    ),
    learnMoreUrl: "https://developers.intercom.com/",
  },
  {
    id: "mixpanel-analytics",
    name: "Mixpanel",
    category: "platforms",
    description: "Product analytics focused on events, retention, and experimentation tie-ins.",
    typicalImportance: O,
    audiences: ["product", "data"],
    keywords: ["analytics", "events", "retention"],
    setupOverview:
      "Mixpanel projects may mirror production traffic — confirm sampling and EU residency settings.",
    setupSteps: steps(
      "Create service account token scoped to projects.",
      "Map event dictionaries before summarization.",
      "Validate cohort export APIs.",
      "Restrict insights APIs if billing-sensitive.",
      "Rotate tokens quarterly.",
    ),
    learnMoreUrl: "https://developer.mixpanel.com/",
  },
  {
    id: "pagerduty-incidents",
    name: "PagerDuty",
    category: "platforms",
    description: "On-call schedules, incident response, and escalation policies.",
    typicalImportance: O,
    audiences: ["engineering", "operations"],
    keywords: ["incidents", "on-call", "SRE"],
    setupOverview:
      "PagerDuty APIs can page humans — never grant mutation scopes broadly to experimental coworkers.",
    setupSteps: steps(
      "Create API keys restricted to read-only incident introspection if summarizing.",
      "Map services and escalation policies explicitly.",
      "Verify audit trails for write attempts.",
      "Dry-run incident notes APIs on sandbox services.",
      "Require human approval paths before auto-ack flows.",
    ),
    learnMoreUrl: "https://developer.pagerduty.com/",
  },
  {
    id: "splunk-cloud",
    name: "Splunk",
    category: "platforms",
    description: "Search and observability platform for logs, metrics, and security analytics.",
    typicalImportance: O,
    audiences: ["engineering", "security", "operations"],
    keywords: ["logs", "SIEM", "search"],
    setupOverview:
      "Splunk searches can exfiltrate secrets from logs — enforce role-based search filters.",
    setupSteps: steps(
      "Issue tokens tied to roles with index/time restrictions.",
      "Disable verbose SPL until reviewed.",
      "Validate KV store vs metrics access separately.",
      "Dry-run saved searches with masked data.",
      "Coordinate with SecOps on correlation searches.",
    ),
    learnMoreUrl: "https://docs.splunk.com/Documentation/SplunkCloud/latest/RESTREF/RESTintro",
  },
  {
    id: "jenkins-automation",
    name: "Jenkins",
    category: "platforms",
    description: "Self-hosted automation server — jobs, pipelines, and plugin ecosystems.",
    typicalImportance: O,
    audiences: ["engineering", "operations"],
    keywords: ["CI", "pipelines", "plugins"],
    setupOverview:
      "Jenkins is high-risk if exposed — require authn/authz on UI and APIs; isolate agents.",
    setupSteps: steps(
      "Create API tokens per automation principal.",
      "Restrict folder/item RBAC.",
      "Disable script console access for automation accounts.",
      "Dry-run build status APIs.",
      "Patch Jenkins monthly.",
    ),
    learnMoreUrl: "https://www.jenkins.io/doc/book/using/remote-access-api/",
  },
  {
    id: "launchdarkly-flags",
    name: "LaunchDarkly",
    category: "platforms",
    description: "Feature flags and experimentation controls across services.",
    typicalImportance: O,
    audiences: ["engineering", "product"],
    keywords: ["feature flags", "rollout"],
    setupOverview:
      "Flag changes can instantly alter customer behavior — separate production tokens from sandbox.",
    setupSteps: steps(
      "Create API access tokens with environment scopes.",
      "Prefer read-only tokens for coworkers summarizing state.",
      "Document approval flow for flag mutations.",
      "Dry-run flag listing APIs.",
      "Alert on accidental global killswitches.",
    ),
    learnMoreUrl: "https://docs.launchdarkly.com/home/api-overview",
  },
  {
    id: "opsgenie-alerts",
    name: "Opsgenie (Jira Service Management)",
    category: "platforms",
    description: "Alert routing and on-call overlaps within Atlassian’s ops stack.",
    typicalImportance: O,
    audiences: ["engineering", "operations"],
    keywords: ["alerts", "on-call"],
    setupOverview:
      "Opsgenie integrates tightly with Jira — reuse OAuth posture where possible.",
    setupSteps: steps(
      "Generate API keys scoped to teams/schedules.",
      "Validate read-only incident APIs.",
      "Map escalation rules before automation touches them.",
      "Dry-run heartbeat integrations separately.",
      "Document paging suppression windows.",
    ),
    learnMoreUrl: "https://docs.opsgenie.com/docs/api-overview",
  },
  {
    id: "braze-messaging",
    name: "Braze",
    category: "platforms",
    description: "Customer engagement across push, email, and in-app messaging.",
    typicalImportance: O,
    audiences: ["gtm", "product"],
    keywords: ["lifecycle", "campaigns"],
    setupOverview:
      "Braze can send regulated communications — align with CAN-SPAM/GDPR programs.",
    setupSteps: steps(
      "Use REST keys scoped to workspaces.",
      "Separate sandbox vs prod workspaces.",
      "Validate subscription group APIs before edits.",
      "Dry-run Canvas/Braze catalog reads.",
      "Maintain approval routing for campaign launches.",
    ),
    learnMoreUrl: "https://www.braze.com/docs/api/",
  },
  {
    id: "mailchimp-campaigns",
    name: "Mailchimp",
    category: "platforms",
    description: "Newsletters and lifecycle email for SMB/SME marketing stacks.",
    typicalImportance: O,
    audiences: ["gtm"],
    keywords: ["email marketing", "newsletter"],
    setupOverview:
      "Audience exports can contain personal data — gate merge fields.",
    setupSteps: steps(
      "Create OAuth app or API key with minimal scopes.",
      "Restrict audiences/lists.",
      "Dry-run campaign reporting APIs.",
      "Verify unsubscribe handling.",
      "Rotate keys after contractor exits.",
    ),
    learnMoreUrl: "https://mailchimp.com/developer/",
  },
  {
    id: "calendly-scheduling",
    name: "Calendly",
    category: "mail_calendar",
    description: "Outbound scheduling links and routing forms for sales + recruiting.",
    typicalImportance: O,
    audiences: ["gtm", "people", "leadership"],
    keywords: ["booking", "calendar"],
    setupOverview:
      "Calendly reveals availability patterns — use team-wide policies for external vs internal event types.",
    setupSteps: steps(
      "Generate personal access token or OAuth client.",
      "Map allowed event types.",
      "Validate webhook signatures for booking notifications.",
      "Dry-run invitee APIs with dummy data.",
      "Disable automatic Zoom creation if not approved.",
    ),
    learnMoreUrl: "https://developer.calendly.com/",
  },
  {
    id: "greenhouse-hiring",
    name: "Greenhouse",
    category: "platforms",
    description: "ATS workflows — reqs, interviews, scorecards, and offer milestones.",
    typicalImportance: O,
    audiences: ["people", "leadership"],
    keywords: ["recruiting", "ATS", "hiring"],
    setupOverview:
      "ATS data is HR-sensitive — restrict harvest connector to anonymized summaries unless counsel approves.",
    setupSteps: steps(
      "Create Harvest API key with partner-approved scopes.",
      "Document which endpoints may be called (candidates vs jobs).",
      "Enable audit trails.",
      "Dry-run sandbox endpoints if Greenhouse provides them.",
      "Establish retention when exporting to other stores.",
    ),
    learnMoreUrl: "https://developers.greenhouse.io/",
  },
  {
    id: "workday-hcm",
    name: "Workday",
    category: "trust",
    description: "HCM / finance suites — org structure, worker data, approvals.",
    typicalImportance: O,
    audiences: ["people", "leadership", "operations"],
    keywords: ["HRIS", "payroll adjacent"],
    prerequisites: ["Typically multi-month integration programs — treat as regulated data by default."],
    setupOverview:
      "Workday integrations almost always involve IA partners — expect certificates and integration system users.",
    setupSteps: steps(
      "Stand up an integration system user with documented SOAP/REST scopes.",
      "Route traffic through approved middleware or IPSec tunnels.",
      "Field-mask sensitive attributes before AI summarization.",
      "Schedule UAT with HRIS owners.",
      "Maintain change windows with Workday release calendar.",
    ),
    learnMoreUrl: "https://developer.workday.com/",
  },
];
