import type {
  ConnectorAudience,
  ConnectorCategory,
  ConnectorDefinition,
  ConnectorTypicalImportance,
} from "./types.js";
import { ADDITIONAL_CONNECTORS } from "./catalog-additions.js";

export const CONNECTOR_CATEGORY_LABELS: Record<ConnectorCategory, string> = {
  collaboration: "Collaboration",
  mail_calendar: "Mail & calendar",
  meetings: "Meetings",
  engineering: "Engineering & source control",
  delivery: "Planning & delivery",
  knowledge: "Knowledge & docs",
  design_research: "Design & research",
  platforms: "Infrastructure & platforms",
  trust: "Identity & trust",
};

export const CONNECTOR_CATEGORY_ORDER: ConnectorCategory[] = [
  "collaboration",
  "mail_calendar",
  "meetings",
  "engineering",
  "delivery",
  "knowledge",
  "design_research",
  "platforms",
  "trust",
];

export const CONNECTOR_AUDIENCE_LABELS: Record<ConnectorAudience, string> = {
  engineering: "Engineering",
  design: "Design",
  product: "Product",
  data: "Data & analytics",
  operations: "Operations & IT",
  gtm: "Go-to-market",
  people: "People & HR",
  security: "Security & compliance",
  leadership: "Leadership",
};

export const CONNECTOR_AUDIENCE_ORDER: ConnectorAudience[] = [
  "engineering",
  "design",
  "product",
  "data",
  "operations",
  "gtm",
  "people",
  "security",
  "leadership",
];

const R = "required" as ConnectorTypicalImportance;
const M = "recommended" as ConnectorTypicalImportance;
const O = "optional" as ConnectorTypicalImportance;

function steps(...lines: string[]): string[] {
  return lines;
}

/** Canonical list of connectable apps and how to wire them. Keep in sync with `doc/connectors-directory.md`. */
const CONNECTOR_CATALOG_CORE: ConnectorDefinition[] = [
  {
    id: "slack",
    stackIcon: "slack",
    name: "Slack",
    category: "collaboration",
    description:
      "Primary channel for coworker presence, DMs, channel reads, and lightweight approvals where your team already works.",
    typicalImportance: R,
    keywords: ["chat", "messaging", "channels", "async"],
    setupOverview:
      "Slack is usually the highest-signal surface for a coworker: channel context, threads, and DMs. Treat the connector as production infrastructure — scope channels deliberately and document which workspaces are in bounds.",
    rolloutNotes: [
      "Decide whether the coworker reads only public channels or also named private channels (invite-only).",
      "Align with legal/comms on retention exports if the coworker summarizes threads.",
      "Keep a single Slack app registration per Bench environment to simplify audits.",
    ],
    prerequisites: ["Workspace admin can approve OAuth apps or custom integrations."],
    authenticationNotes: [
      "Use a Slack workspace admin or owner account for the initial OAuth consent.",
      "Least-privilege: grant only the scopes Bench lists; avoid legacy bot tokens unless policy requires them.",
      "After consent, rotate or revoke test tokens in Slack app management if you ran pilots on production workspaces.",
    ],
    setupSteps: steps(
      "Confirm Slack workspace URL and that HRIT allows third-party Slack apps.",
      "From Bench connector settings (when enabled), start Slack OAuth and sign in as a workspace admin.",
      "Approve requested scopes (typically channels:read, channels:history, chat:write, users:read, im:history).",
      "Pick default channels the coworker may join; restrict with private channel invites as needed.",
      "Send a test message from Bench to a private channel to verify token health.",
    ),
    learnMoreUrl: "https://api.slack.com/authentication/oauth-v2",
  },
  {
    id: "microsoft-teams",
    stackIcon: "microsoft",
    name: "Microsoft Teams",
    category: "collaboration",
    description: "Chat and collaboration for Microsoft 365–centric organizations.",
    typicalImportance: R,
    prerequisites: ["Azure AD app registration permissions for Teams bot or Graph scopes."],
    setupSteps: steps(
      "Register or select an Azure AD application for Bench / your tenant connector.",
      "Grant Microsoft Graph permissions aligned to chat read/post (e.g., ChannelMessage.Read.All, Chat.ReadWrite per policy).",
      "Complete admin consent in Entra ID.",
      "Install the connector app to the target team or scope channel membership.",
      "Post a verification message and confirm the coworker can read thread history per policy.",
    ),
    learnMoreUrl: "https://learn.microsoft.com/graph/teams-concept-overview",
  },
  {
    id: "google-chat",
    stackIcon: "google",
    name: "Google Chat",
    category: "collaboration",
    description: "Spaces and DMs in Google Workspace.",
    typicalImportance: M,
    setupSteps: steps(
      "Enable Google Chat API for the Workspace project.",
      "Configure OAuth consent and publish internal app if required by policy.",
      "Authorize Chat scopes for space membership and messaging.",
      "Add the coworker bot or service account to relevant spaces.",
      "Verify a test mention or DM delivers successfully.",
    ),
    learnMoreUrl: "https://developers.google.com/chat/api/guides/auth",
  },
  {
    id: "mattermost",
    name: "Mattermost",
    category: "collaboration",
    description: "Self-hosted or cloud team messaging for regulated environments.",
    typicalImportance: M,
    setupSteps: steps(
      "Create a personal access token or OAuth application per Mattermost security policy.",
      "Record server URL, team, and channel IDs the coworker should use.",
      "Scope token to minimum channels and post permissions.",
      "Validate webhook or bot posting with a dry-run message.",
    ),
    learnMoreUrl: "https://developers.mattermost.com/integrate/reference/rest-api/",
  },
  {
    id: "webex-messaging",
    name: "Webex (Messaging)",
    category: "collaboration",
    description: "Enterprise messaging where Cisco Webex is standard.",
    typicalImportance: O,
    setupSteps: steps(
      "Create a Webex integration app with bot token in Control Hub.",
      "Add required scopes for messaging and membership.",
      "Invite the bot to target spaces.",
      "Run a connectivity test from Bench connector health (when available).",
    ),
    learnMoreUrl: "https://developer.webex.com/docs/bots",
  },
  {
    id: "outlook-m365",
    stackIcon: "microsoft",
    name: "Outlook / Microsoft 365",
    category: "mail_calendar",
    description: "Mailbox and calendar on Microsoft 365 — email triage, invites, and scheduling.",
    typicalImportance: R,
    authenticationNotes: [
      "Microsoft Entra admin consent is often required before delegated users can authorize Graph.",
      "Prefer dedicated automation accounts or shared mailboxes with documented retention.",
      "Restrict reply/send identities so coworkers cannot spoof executives.",
    ],
    setupSteps: steps(
      "Choose shared mailbox vs delegated user per security policy.",
      "Start Graph OAuth with Mail.Read, Mail.Send, Calendars.ReadWrite (trim to least privilege).",
      "Complete admin consent if the tenant requires it.",
      "Configure send-as / reply-from addresses if different from login.",
      "Send a calendar hold and a test email to confirm bidirectional flow.",
    ),
    learnMoreUrl: "https://learn.microsoft.com/graph/api/resources/mail-api-overview",
  },
  {
    id: "gmail-google-workspace",
    stackIcon: "google",
    name: "Gmail & Google Calendar",
    category: "mail_calendar",
    description: "Google Workspace mail and calendar for routing and meetings.",
    typicalImportance: R,
    setupSteps: steps(
      "Create OAuth client in Google Cloud console restricted to your Workspace org.",
      "Enable Gmail and Calendar APIs.",
      "Request scopes (e.g., gmail.modify, calendar.events) per least-privilege review.",
      "Run OAuth as the mailbox owner or admin-delegated account.",
      "Verify receive, label/filter behavior, and event creation in a test calendar.",
    ),
    learnMoreUrl: "https://developers.google.com/workspace/gmail/api/guides",
  },
  {
    id: "imap-smtp",
    name: "IMAP / SMTP (generic)",
    category: "mail_calendar",
    description: "Apple Mail, Fastmail, or other standards-based providers when OAuth is unavailable.",
    typicalImportance: O,
    prerequisites: ["Prefer OAuth providers when possible; app passwords increase operational risk."],
    setupSteps: steps(
      "Collect IMAP/SMTP hostnames, ports, and TLS requirements.",
      "Provision an app-specific password or service credential per vendor guidance.",
      "Store secrets in Bench secret store / vault integration — never in repo.",
      "Send and fetch a test message; monitor for rate limits.",
    ),
  },
  {
    id: "zoom",
    name: "Zoom",
    category: "meetings",
    description: "Schedule and join Zoom meetings; capture links and recordings where policy allows.",
    typicalImportance: M,
    setupSteps: steps(
      "Create a Server-to-Server OAuth app or OAuth app in Zoom Marketplace as required.",
      "Grant meeting create/read scopes appropriate for scheduling assistants.",
      "Connect a service account or delegated host user.",
      "Schedule a test meeting and confirm join URL flows back to your chat system.",
    ),
    learnMoreUrl: "https://developers.zoom.us/docs/api/",
  },
  {
    id: "google-meet",
    stackIcon: "google",
    name: "Google Meet",
    category: "meetings",
    description: "Meetings tied to Google Calendar events.",
    typicalImportance: M,
    setupSteps: steps(
      "Ensure Calendar API access from the Gmail & Calendar connector.",
      "Confirm Workspace policy allows external guests if coworkers invite contractors.",
      "Validate Meet link generation on created events.",
    ),
    learnMoreUrl: "https://developers.google.com/workspace/calendar/api/guides/overview",
  },
  {
    id: "microsoft-teams-meetings",
    stackIcon: "microsoft",
    name: "Microsoft Teams meetings",
    category: "meetings",
    description: "Calendar-backed Teams meetings via Graph.",
    typicalImportance: M,
    setupSteps: steps(
      "Use the same Entra app as Teams messaging where possible; add OnlineMeetings permissions if scheduling.",
      "Verify application access policy allows meeting creation.",
      "Create a test meeting series and inspect attendee emails.",
    ),
    learnMoreUrl: "https://learn.microsoft.com/graph/api/resources/onlinemeeting",
  },
  {
    id: "github",
    stackIcon: "github",
    name: "GitHub",
    category: "engineering",
    description: "Repos, PRs, issues, Actions signals — primary toolchain for engineering coworkers.",
    typicalImportance: M,
    authenticationNotes: [
      "GitHub Apps support finer repo allowlists than classic PATs — prefer Apps for production.",
      "Use org-level installation with explicit repository selection.",
      "Enable SSO authorization if your org enforces SAML.",
    ],
    setupSteps: steps(
      "Create a GitHub App or fine-grained PAT scoped to required orgs/repos.",
      "Grant contents, pull_requests, issues (and actions read if needed) at minimum.",
      "Install the app on the organization with repo allowlists.",
      "Verify clone/fetch via sandbox environment if coworkers execute code.",
      "Open a test PR comment webhook or poll to confirm API access.",
    ),
    learnMoreUrl: "https://docs.github.com/apps/creating-github-apps",
  },
  {
    id: "gitlab",
    stackIcon: "gitlab",
    name: "GitLab",
    category: "engineering",
    description: "Merge requests, CI visibility, and repo operations on GitLab SaaS or self-managed.",
    typicalImportance: M,
    setupSteps: steps(
      "Create a project access token or group token with API scope per GitLab version.",
      "Record base URL for self-managed instances.",
      "Restrict token to projects/groups the coworker needs.",
      "Validate MR comment and pipeline read operations.",
    ),
    learnMoreUrl: "https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html",
  },
  {
    id: "bitbucket",
    stackIcon: "bitbucket",
    name: "Bitbucket Cloud / Data Center",
    category: "engineering",
    description: "Atlassian-flavored PRs and repos.",
    typicalImportance: O,
    setupSteps: steps(
      "Create OAuth consumer or HTTP access token with repository read/write as needed.",
      "Map workspaces and repos explicitly.",
      "Test PR retrieval and comment posting on a sandbox repo.",
    ),
    learnMoreUrl: "https://developer.atlassian.com/cloud/bitbucket/oauth-2/",
  },
  {
    id: "azure-repos",
    stackIcon: "azure",
    name: "Azure Repos",
    category: "engineering",
    description: "Git repos and PRs inside Azure DevOps.",
    typicalImportance: O,
    setupSteps: steps(
      "Create PAT or Azure DevOps OAuth app with Code (read/write) scoped.",
      "Note organization and project URLs.",
      "Validate PR threads and branch policies visibility.",
    ),
    learnMoreUrl: "https://learn.microsoft.com/azure/devops/organizations/accounts/use-personal-access-tokens",
  },
  {
    id: "jira",
    stackIcon: "jira",
    name: "Jira",
    category: "delivery",
    description: "Issue transitions, comments, sprint hygiene — common enterprise backbone.",
    typicalImportance: M,
    setupSteps: steps(
      "Create Atlassian OAuth app or API token for Cloud / PAT for Data Center per policy.",
      "Capture cloud site URL or DC base URL.",
      "Scope to projects and issue types the coworker may touch.",
      "Verify create/transition permissions with a dummy ticket.",
    ),
    learnMoreUrl: "https://developer.atlassian.com/cloud/jira/platform/rest/v3/",
  },
  {
    id: "linear",
    stackIcon: "linear",
    name: "Linear",
    category: "delivery",
    description: "Modern issue tracking for product/engineering teams.",
    typicalImportance: M,
    setupSteps: steps(
      "Create OAuth API key or OAuth application per Linear docs.",
      "Grant access to the relevant workspace and teams.",
      "Validate issue create/update and comment flows.",
    ),
    learnMoreUrl: "https://developers.linear.app/docs/graphql/working-with-the-api",
  },
  {
    id: "asana",
    stackIcon: "asana",
    name: "Asana",
    category: "delivery",
    description: "Tasks and projects for cross-functional coordination.",
    typicalImportance: O,
    setupSteps: steps(
      "Register OAuth app and capture PAT if allowed.",
      "Restrict to portfolios/projects needed.",
      "Run task create and assignment smoke tests.",
    ),
    learnMoreUrl: "https://developers.asana.com/docs/oauth",
  },
  {
    id: "azure-devops-boards",
    stackIcon: "azure",
    name: "Azure Boards",
    category: "delivery",
    description: "Work items linked to Azure DevOps repos and pipelines.",
    typicalImportance: O,
    setupSteps: steps(
      "Reuse Azure DevOps PAT with Work Items (read/write) scope.",
      "Map area paths and iteration permissions.",
      "Validate WIQL queries or REST updates on a test item.",
    ),
    learnMoreUrl: "https://learn.microsoft.com/azure/devops/integrate/",
  },
  {
    id: "github-issues",
    stackIcon: "github",
    name: "GitHub Issues",
    category: "delivery",
    description: "Lightweight tracking alongside GitHub PRs.",
    typicalImportance: M,
    setupSteps: steps(
      "Reuse GitHub App / fine-grained token with Issues permission on target repos.",
      "Confirm issue labels and milestones visibility.",
    ),
    learnMoreUrl: "https://docs.github.com/rest/issues/issues",
  },
  {
    id: "confluence",
    stackIcon: "atlassian",
    name: "Confluence",
    category: "knowledge",
    description: "Enterprise wiki — specs, runbooks, decision logs.",
    typicalImportance: M,
    setupSteps: steps(
      "Use Atlassian OAuth aligned with Jira where possible.",
      "Scope to spaces the coworker may read or edit.",
      "Verify page search and comment capabilities.",
    ),
    learnMoreUrl: "https://developer.atlassian.com/cloud/confluence/rest/v2/",
  },
  {
    id: "notion",
    stackIcon: "notion",
    name: "Notion",
    category: "knowledge",
    description: "Flexible docs and databases for product teams.",
    typicalImportance: M,
    setupSteps: steps(
      "Create Notion integration and capture internal integration secret.",
      "Share specific pages/databases with the integration.",
      "Validate read vs write needs — avoid full workspace scope.",
    ),
    learnMoreUrl: "https://developers.notion.com/docs/getting-started",
  },
  {
    id: "google-drive",
    stackIcon: "google",
    name: "Google Drive & Docs",
    category: "knowledge",
    description: "Canonical files and collaborative docs in Workspace.",
    typicalImportance: M,
    setupSteps: steps(
      "Extend Google OAuth with Drive/Docs scopes as needed.",
      "Prefer shared drives with explicit membership.",
      "Verify export formats if coworkers attach artifacts to issues.",
    ),
    learnMoreUrl: "https://developers.google.com/workspace/drive/api/guides/about-sdk",
  },
  {
    id: "sharepoint",
    stackIcon: "microsoft",
    name: "SharePoint / OneDrive",
    category: "knowledge",
    description: "Microsoft 365 document libraries and lists.",
    typicalImportance: O,
    setupSteps: steps(
      "Use Graph Sites.Selected or broader Sites.Read.All per risk review.",
      "Register site URLs and document libraries.",
      "Validate upload/download paths align with DLP policies.",
    ),
    learnMoreUrl: "https://learn.microsoft.com/graph/api/resources/sharepoint",
  },
  {
    id: "docker",
    stackIcon: "docker",
    name: "Docker",
    category: "platforms",
    description:
      "Container images and local/remote Docker hosts for build, test, and deployment automation.",
    typicalImportance: M,
    prerequisites: ["Prefer registry credentials with least privilege; avoid mounting Docker sockets broadly."],
    setupSteps: steps(
      "Choose registry (Docker Hub, ECR, GCR, ACR, etc.) and create a robot account or scoped PAT.",
      "Document base images approved by security; pin digests where policy requires.",
      "Configure Bench or adapter access with read-only pulls unless pushes are explicitly needed.",
      "Run a non-production image pull and `docker inspect`-style health check from the automation environment.",
      "Rotate registry credentials on a fixed calendar.",
    ),
    learnMoreUrl: "https://docs.docker.com/develop/develop-images/dockerfile_best-practices/",
  },
  {
    id: "kubernetes",
    stackIcon: "kubernetes",
    name: "Kubernetes",
    category: "platforms",
    description: "Cluster API access for deployments, logs, and resource inspection where coworkers automate infra tasks.",
    typicalImportance: M,
    prerequisites: ["Highly sensitive — restrict to namespaces and verbs aligned with RBAC reviews."],
    setupSteps: steps(
      "Create a dedicated service account per environment with namespace-scoped RoleBindings.",
      "Issue kubeconfig or OIDC-based credentials; store secrets in a vault integration.",
      "Verify read-only `get/list` before granting apply/exec.",
      "Document blast radius if coworkers can mutate workloads.",
      "Audit RBAC quarterly or on org changes.",
    ),
    learnMoreUrl: "https://kubernetes.io/docs/reference/access-authn-authz/rbac/",
  },
  {
    id: "terraform",
    stackIcon: "terraform",
    name: "Terraform / OpenTofu",
    category: "platforms",
    description: "Infrastructure-as-code plans and applies for cloud resources (often paired with policy-as-code).",
    typicalImportance: O,
    setupSteps: steps(
      "Use remote state with locking; restrict state bucket permissions.",
      "Provision CI OIDC or short-lived tokens for plan/apply — avoid long-lived cloud keys on laptops.",
      "Run speculative plans in sandbox accounts before production applies.",
      "Attach Sentinel/OPA or cloud policy checks if required by governance.",
    ),
    learnMoreUrl: "https://developer.hashicorp.com/terraform/docs",
  },
  {
    id: "pulumi",
    stackIcon: "pulumi",
    name: "Pulumi",
    category: "platforms",
    description: "General-purpose IaC with familiar languages — stacks and outputs for automation coworkers.",
    typicalImportance: O,
    setupSteps: steps(
      "Create a Pulumi access token scoped to the target organization/stack.",
      "Configure encrypted secrets backends per vendor guidance.",
      "Dry-run previews (`pulumi preview`) before granting apply.",
    ),
    learnMoreUrl: "https://www.pulumi.com/docs/",
  },
  {
    id: "hashicorp-vault",
    stackIcon: "vault",
    name: "HashiCorp Vault",
    category: "platforms",
    description: "Central secret lease and dynamic credentials — preferred home for tokens coworkers retrieve at runtime.",
    typicalImportance: M,
    setupSteps: steps(
      "Enable namespaces or mounts per team; use policies as code.",
      "Prefer AppRole, Kubernetes auth, or OIDC over static tokens.",
      "Tune TTLs and revocation paths; exercise break-glass procedures.",
    ),
    learnMoreUrl: "https://developer.hashicorp.com/vault/docs",
  },
  {
    id: "rabbitmq",
    stackIcon: "rabbitmq",
    name: "RabbitMQ",
    category: "platforms",
    description: "Message broker for async workflows, task queues, and integration glue.",
    typicalImportance: O,
    setupSteps: steps(
      "Create least-privilege users limited to specific vhosts and queues.",
      "Enable TLS and credential rotation.",
      "Smoke-test publish/consume from the coworker runtime.",
    ),
    learnMoreUrl: "https://www.rabbitmq.com/documentation.html",
  },
  {
    id: "mongodb",
    stackIcon: "mongodb",
    name: "MongoDB",
    category: "platforms",
    description: "Document database access for analytics, ETL, or operational read assistants.",
    typicalImportance: O,
    setupSteps: steps(
      "Prefer database users scoped to collections; enable auditing where available.",
      "Use TLS and IP allowlists or private networking.",
      "Confirm read-only vs read-write requirements explicitly.",
    ),
    learnMoreUrl: "https://www.mongodb.com/docs/manual/security/",
  },
  {
    id: "redis",
    stackIcon: "redis",
    name: "Redis / Valkey",
    category: "platforms",
    description: "Caches, queues, and ephemeral state — common companion to web services.",
    typicalImportance: O,
    setupSteps: steps(
      "Disable dangerous commands in production (FLUSHALL, CONFIG, etc.) via ACLs.",
      "Require AUTH/TLS; isolate instances per environment.",
      "Document eviction and persistence expectations.",
    ),
    learnMoreUrl: "https://redis.io/docs/latest/operate/rs/security/",
  },
  {
    id: "postgresql",
    stackIcon: "postgresql",
    name: "PostgreSQL",
    category: "platforms",
    description: "Relational reads/writes for reporting, migrations assistance, or app data surfacing.",
    typicalImportance: M,
    setupSteps: steps(
      "Create role-based users with explicit schema grants.",
      "Force SSL; route through bastion or private link if required.",
      "Snapshot anonymization rules before granting broad SELECT.",
    ),
    learnMoreUrl: "https://www.postgresql.org/docs/current/sql-grant.html",
  },
  {
    id: "mysql",
    stackIcon: "mysql",
    name: "MySQL / MariaDB",
    category: "platforms",
    description: "Common relational store for LAMP-style stacks and SaaS replicas.",
    typicalImportance: O,
    setupSteps: steps(
      "Grant minimal privileges per database; avoid SUPER.",
      "Enable TLS and rotate passwords via vault where possible.",
    ),
    learnMoreUrl: "https://dev.mysql.com/doc/refman/en/access-control.html",
  },
  {
    id: "snowflake",
    stackIcon: "snowflake",
    name: "Snowflake",
    category: "platforms",
    description: "Warehouse analytics SQL — governed access to curated datasets.",
    typicalImportance: O,
    setupSteps: steps(
      "Use OAuth or key-pair users scoped to warehouses and roles.",
      "Apply row access policies and masking as mandated.",
      "Log queries for sensitive datasets.",
    ),
    learnMoreUrl: "https://docs.snowflake.com/en/user-guide/security",
  },
  {
    id: "elasticsearch",
    stackIcon: "elastic",
    name: "Elasticsearch / OpenSearch",
    category: "platforms",
    description: "Search and log indices — powerful reads; align with retention and PII policies.",
    typicalImportance: O,
    setupSteps: steps(
      "Scope API keys to indices and minimal verbs.",
      "Separate observability vs application search clusters when feasible.",
      "Confirm ILM / retention vs legal hold processes.",
    ),
    learnMoreUrl: "https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api.html",
  },
  {
    id: "aws",
    stackIcon: "aws",
    name: "Amazon Web Services (AWS)",
    category: "platforms",
    description: "Broad cloud API surface — compute, storage, IAM-aware automation for engineering coworkers.",
    typicalImportance: M,
    prerequisites: ["Prefer scoped IAM roles (OIDC from CI) over long-lived access keys."],
    setupSteps: steps(
      "Define OU/account boundaries and baseline SCPs.",
      "Issue permission boundaries or dedicated roles per coworker workload.",
      "Enable CloudTrail org trails and detective alerts on risky API verbs.",
      "Validate least privilege with IAM Access Analyzer or policy simulations.",
    ),
    learnMoreUrl: "https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html",
  },
  {
    id: "google-cloud",
    stackIcon: "gcloud",
    name: "Google Cloud (GCP)",
    category: "platforms",
    description: "GCP projects and APIs — BigQuery, GKE, Cloud Storage, IAM bindings.",
    typicalImportance: O,
    setupSteps: steps(
      "Use workload identity federation instead of JSON keys where possible.",
      "Folder/project IAM with custom roles for narrow scopes.",
      "Enable organization policies for domain restricted sharing.",
    ),
    learnMoreUrl: "https://cloud.google.com/iam/docs/best-practices",
  },
  {
    id: "microsoft-azure-cloud",
    stackIcon: "azure",
    name: "Microsoft Azure (cloud resources)",
    category: "platforms",
    description: "Subscriptions, resource groups, Key Vault, AKS — distinct from Entra directory-only flows.",
    typicalImportance: O,
    setupSteps: steps(
      "Prefer managed identities and Azure RBAC over shared owners.",
      "Scope service principals to resource groups.",
      "Enable Defender for Cloud baseline recommendations where mandated.",
    ),
    learnMoreUrl: "https://learn.microsoft.com/azure/role-based-access-control/overview",
  },
  {
    id: "digitalocean",
    stackIcon: "digitalocean",
    name: "DigitalOcean",
    category: "platforms",
    description: "Simpler cloud VMs, Kubernetes, and managed databases for smaller teams.",
    typicalImportance: O,
    setupSteps: steps(
      "Create scoped API tokens with expiry.",
      "Tag resources per team for chargeback.",
    ),
    learnMoreUrl: "https://docs.digitalocean.com/reference/api/create-personal-access-token/",
  },
  {
    id: "cloudflare",
    stackIcon: "cloudflare",
    name: "Cloudflare",
    category: "platforms",
    description: "DNS, CDN, WAF, Workers — edge configuration and traffic visibility.",
    typicalImportance: O,
    setupSteps: steps(
      "Use API tokens scoped to zone or account operations required.",
      "Require MFA on dashboard owners.",
      "Document rate limits and firewall rules ownership.",
    ),
    learnMoreUrl: "https://developers.cloudflare.com/fundamentals/api/get-started/create-token/",
  },
  {
    id: "datadog",
    stackIcon: "datadog",
    name: "Datadog",
    category: "platforms",
    description: "Metrics, traces, logs, and monitors — operational context for incident coworkers.",
    typicalImportance: M,
    setupSteps: steps(
      "Create restricted API/application keys per use case.",
      "Align RBAC teams with Bench teams.",
      "Redact sensitive tags and attributes at ingestion.",
    ),
    learnMoreUrl: "https://docs.datadoghq.com/account_management/api-app-keys/",
  },
  {
    id: "grafana",
    stackIcon: "grafana",
    name: "Grafana",
    category: "platforms",
    description: "Dashboards across Prometheus/Loki/Tempo and vendor datasources.",
    typicalImportance: O,
    setupSteps: steps(
      "Use Grafana RBAC and folder permissions.",
      "Prefer read-only datasources for assistants unless annotated writes are approved.",
    ),
    learnMoreUrl: "https://grafana.com/docs/grafana/latest/administration/roles-and-permissions/",
  },
  {
    id: "prometheus",
    stackIcon: "prometheus",
    name: "Prometheus",
    category: "platforms",
    description: "Time-series metrics collection — often paired with Kubernetes service discovery.",
    typicalImportance: O,
    setupSteps: steps(
      "Protect Prometheus endpoints with auth or network policies.",
      "Limit remote write/read surfaces.",
    ),
    learnMoreUrl: "https://prometheus.io/docs/prometheus/latest/security/",
  },
  {
    id: "nginx",
    stackIcon: "nginx",
    name: "NGINX",
    category: "platforms",
    description: "Reverse proxy, ingress, and static delivery — config references for platform coworkers.",
    typicalImportance: O,
    setupSteps: steps(
      "Treat configs as code in Git with review.",
      "Separate prod vs non-prod upstream definitions.",
    ),
    learnMoreUrl: "https://docs.nginx.com/nginx/admin-guide/security-controls/",
  },
  {
    id: "circleci",
    stackIcon: "circleci",
    name: "CircleCI",
    category: "platforms",
    description: "Hosted CI pipelines — contexts, OIDC to clouds, and artifact access.",
    typicalImportance: O,
    setupSteps: steps(
      "Rotate project and personal API tokens; prefer OIDC project roles.",
      "Restrict contexts to teams.",
    ),
    learnMoreUrl: "https://circleci.com/docs/security/",
  },
  {
    id: "vercel",
    stackIcon: "vercel",
    name: "Vercel",
    category: "platforms",
    description: "Frontend deployments, previews, and edge functions.",
    typicalImportance: O,
    setupSteps: steps(
      "Scope tokens to teams/projects; enable SSO if available.",
      "Review environment variable classifications.",
    ),
    learnMoreUrl: "https://vercel.com/docs/security",
  },
  {
    id: "netlify",
    stackIcon: "netlify",
    name: "Netlify",
    category: "platforms",
    description: "Jamstack hosting, builds, and serverless functions.",
    typicalImportance: O,
    setupSteps: steps(
      "Use minimal-scope personal access tokens or Git integration only.",
      "Separate production vs preview sensitive env vars.",
    ),
    learnMoreUrl: "https://docs.netlify.com/security/",
  },
  {
    id: "heroku",
    stackIcon: "heroku",
    name: "Heroku",
    category: "platforms",
    description: "PaaS apps and add-ons — useful for smaller services and review apps.",
    typicalImportance: O,
    setupSteps: steps(
      "Enable SSO and MFA on the Heroku team.",
      "Rotate API keys; avoid sharing production credentials.",
    ),
    learnMoreUrl: "https://devcenter.heroku.com/categories/security",
  },
  {
    id: "sentry",
    stackIcon: "sentry",
    name: "Sentry",
    category: "platforms",
    description: "Error tracking and performance issues — triage assistance for engineering coworkers.",
    typicalImportance: O,
    setupSteps: steps(
      "Use organization tokens with event:read scopes where possible.",
      "Scrub PII via Relay rules before ingestion when required.",
    ),
    learnMoreUrl: "https://docs.sentry.io/product/accounts/auth/",
  },
  {
    id: "new-relic",
    stackIcon: "newrelic",
    name: "New Relic",
    category: "platforms",
    description: "APM and observability APIs for dashboards and NRQL queries.",
    typicalImportance: O,
    setupSteps: steps(
      "Create user keys with explicit account scope.",
      "Align with data governance for NRQL exports.",
    ),
    learnMoreUrl: "https://docs.newrelic.com/docs/apis/intro-apis/new-relic-api-keys/",
  },
  {
    id: "stripe",
    stackIcon: "stripe",
    name: "Stripe",
    category: "platforms",
    description: "Payments and billing primitives — restrict to test mode until explicitly approved for live.",
    typicalImportance: O,
    prerequisites: ["Finance and fraud review before any live-secret access."],
    setupSteps: steps(
      "Use restricted API keys per capability (customers vs payouts).",
      "Prefer Stripe Connect test environments for integration dev.",
      "Log and alert on live-mode key usage.",
    ),
    learnMoreUrl: "https://stripe.com/docs/security",
  },
  {
    id: "twilio",
    stackIcon: "twilio",
    name: "Twilio",
    category: "platforms",
    description: "SMS, voice, and messaging APIs — strong abuse and spend controls required.",
    typicalImportance: O,
    prerequisites: ["Often requires legal/comms approval for customer-facing sends."],
    setupSteps: steps(
      "Use subaccounts per environment; cap monthly spend.",
      "Rotate API keys; restrict geographic permissions if applicable.",
    ),
    learnMoreUrl: "https://www.twilio.com/docs/usage/security",
  },
  {
    id: "salesforce",
    stackIcon: "salesforce",
    name: "Salesforce",
    category: "platforms",
    description: "CRM objects, flows, and reporting — common GTM automation surface.",
    typicalImportance: O,
    setupSteps: steps(
      "Use OAuth connected apps with minimal scopes.",
      "Apply field-level security and sharing rules reviews.",
    ),
    learnMoreUrl: "https://developer.salesforce.com/docs/atlas.en-us.securityImplGuide.meta/securityImplGuide/",
  },
  {
    id: "openapi-generic",
    stackIcon: "openapi",
    name: "OpenAPI / REST (generic)",
    category: "platforms",
    description: "Internal or vendor HTTP APIs documented via OpenAPI — pattern for bespoke integrations.",
    typicalImportance: O,
    setupSteps: steps(
      "Publish machine-readable OpenAPI with auth schemes documented.",
      "Issue service tokens with TTL and explicit audience.",
      "Rate-limit and monitor coworker calls like any other client.",
    ),
    learnMoreUrl: "https://swagger.io/specification/",
  },
  {
    id: "graphql-generic",
    stackIcon: "graphql",
    name: "GraphQL (generic)",
    category: "platforms",
    description: "Typed API graphs — enforce complexity limits and auth at the gateway.",
    typicalImportance: O,
    setupSteps: steps(
      "Put authentication at the gateway; disable introspection in production if policy demands.",
      "Configure query cost analysis and pagination defaults.",
    ),
    learnMoreUrl: "https://graphql.org/learn/security/",
  },
  {
    id: "okta",
    stackIcon: "okta",
    name: "Okta (SSO directory)",
    category: "trust",
    description: "People and group discovery for access provisioning narratives — complements Bench SSO.",
    typicalImportance: O,
    prerequisites: ["Usually coordinated with IdP admin — not required for every coworker."],
    setupSteps: steps(
      "Create OAuth service client with read-only users/groups scopes where applicable.",
      "Document which groups map to Bench teams or connector scopes.",
      "Schedule periodic token rotation.",
    ),
    learnMoreUrl: "https://developer.okta.com/docs/api/",
  },
  {
    id: "azure-ad",
    stackIcon: "azure",
    name: "Microsoft Entra ID (Azure AD)",
    category: "trust",
    description: "Directory and conditional access context for Microsoft-centric fleets.",
    typicalImportance: O,
    setupSteps: steps(
      "Reuse enterprise app registration with Directory.Read.All only if justified.",
      "Coordinate conditional access exclusions for automation principals if needed.",
    ),
    learnMoreUrl: "https://learn.microsoft.com/graph/api/overview",
  },
  {
    id: "auth0",
    stackIcon: "auth0",
    name: "Auth0 (Okta Customer Identity)",
    category: "trust",
    description: "Application login, MFA, and social/enterprise connections — developer-centric IAM.",
    typicalImportance: O,
    setupSteps: steps(
      "Create machine-to-machine or RBAC-scoped management tokens.",
      "Separate dev/stage/prod tenants.",
      "Review attack protection and anomaly detection defaults.",
    ),
    learnMoreUrl: "https://auth0.com/docs/secure",
  },
];

export const CONNECTOR_CATALOG: ConnectorDefinition[] = [...CONNECTOR_CATALOG_CORE, ...ADDITIONAL_CONNECTORS];

const byId = new Map<string, ConnectorDefinition>();
for (const c of CONNECTOR_CATALOG) {
  if (byId.has(c.id)) throw new Error(`Duplicate connector id: ${c.id}`);
  byId.set(c.id, c);
}

export function getConnectorById(id: string): ConnectorDefinition | undefined {
  return byId.get(id);
}

export function listConnectorsByCategory(category: ConnectorCategory): ConnectorDefinition[] {
  return CONNECTOR_CATALOG.filter((c) => c.category === category);
}

export function groupedConnectors(): Map<ConnectorCategory, ConnectorDefinition[]> {
  const map = new Map<ConnectorCategory, ConnectorDefinition[]>();
  for (const cat of CONNECTOR_CATEGORY_ORDER) {
    map.set(cat, []);
  }
  for (const c of CONNECTOR_CATALOG) {
    map.get(c.category)!.push(c);
  }
  return map;
}
